//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoSunshineBouquet.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBSBProductoEntities1 : DbContext
    {
        public DBSBProductoEntities1()
            : base("name=DBSBProductoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grado> Grado { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<ProductoGrado> ProductoGrado { get; set; }
        public virtual DbSet<ProductoVariedad> ProductoVariedad { get; set; }
        public virtual DbSet<Variedad> Variedad { get; set; }
        public virtual DbSet<Archivo> Archivo { get; set; }
    }
}
